const ADJECTIVES = [
  "Arcane",
  "Bold",
  "Brisk",
  "Candid",
  "Clever",
  "Crisp",
  "Cryptic",
  "Cunning",
  "Daring",
  "Deft",
  "Dry",
  "Eloquent",
  "Epic",
  "Fabled",
  "Fierce",
  "Fluent",
  "Gilded",
  "Grand",
  "Hushed",
  "Keen",
  "Lavish",
  "Lexical",
  "Lilting",
  "Lofty",
  "Lucid",
  "Lyrical",
  "Muted",
  "Mystic",
  "Nimble",
  "Noble",
  "Odd",
  "Ornate",
  "Pithy",
  "Plucky",
  "Poetic",
  "Primal",
  "Prose",
  "Quaint",
  "Quiet",
  "Rare",
  "Regal",
  "Sly",
  "Shrewd",
  "Stark",
  "Stoic",
  "Swift",
  "Terse",
  "Veiled",
  "Verbose",
  "Vivid",
  "Wily",
  "Witty",
  "Wry",
  "Zesty",
];

const NOUNS = [
  "Acrostic",
  "Allegory",
  "Anagram",
  "Ballad",
  "Cipher",
  "Clause",
  "Codex",
  "Couplet",
  "Dialect",
  "Diction",
  "Elegy",
  "Enigma",
  "Epistle",
  "Fable",
  "Folio",
  "Gambit",
  "Glyph",
  "Grimoire",
  "Haiku",
  "Idiom",
  "Lexicon",
  "Limerick",
  "Mantra",
  "Maxim",
  "Memoir",
  "Motif",
  "Novella",
  "Ode",
  "Opus",
  "Palindrome",
  "Parable",
  "Parlance",
  "Phrase",
  "Proverb",
  "Quill",
  "Quatrain",
  "Riddle",
  "Rune",
  "Saga",
  "Scrawl",
  "Scroll",
  "Sonnet",
  "Strophe",
  "Syntax",
  "Thesis",
  "Tome",
  "Trope",
  "Verse",
  "Vignette",
  "Vowel",
  "Yarn",
];

const hashString = (value: string): number => {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
};

export const getGameLabel = (gameId: string): string => {
  const hash = hashString(gameId);
  const adjective = ADJECTIVES[hash % ADJECTIVES.length];
  const noun = NOUNS[(hash >>> 8) % NOUNS.length];
  const code = hash.toString(16).padStart(8, "0").slice(0, 4).toUpperCase();
  return `${adjective} ${noun} #${code}`;
};
